<?php
return [
    'GET' => [
        '/' => ['HomeController', 'index'],
        '/login' => ['AuthController', 'index'],
        '/logout' => ['AuthController', 'logout'],
        '/scan' => ['ScanController', 'index'],
        '/dashboard' => ['DashboardController', 'index'],
        '/manualEncoding' => ['ManualEncodingController', 'index'],
        '/historical' => ['HistoricalController', 'index'],
        '/absent' => ['AbsenceController', 'index'],
        '/search' => ['SearchController', 'index'],
        '/management' => ['ManagementController', 'index'],
        '/gestion' => ['ManagementController', 'index'],

        // API Routes
            '/api/login' => ['AuthController', 'verify'],
            '/api/logout' => ['AuthController', 'logout'],
        '/api/students' => ['StudentsController', 'getAll'],
        '/api/students/search' => ['StudentsController', 'search'],
        '/api/students/{id}' => ['StudentsController', 'getById'],
        '/api/movements/search-by-student' => ['MovementsController', 'searchByStudent'],
        '/api/movements' => ['MovementsController', 'getAll'],
        '/api/movements/reasons' => ['MovementsController', 'getReasonOptions'],
        '/api/movements/student/{id}' => ['MovementsController', 'getByStudentId'],
        '/api/users' => ['UsersController', 'getAll'],
        '/api/passages' => ['HistoricalController', 'getPassages'],
        '/api/stats/dates' => ['HistoricalController', 'getStatsByDate'],
        '/api/stats' => ['DashboardController', 'getStats'],
        '/api/absents/today' => ['AbsenceController', 'getTodayAbsents'],
        '/api/absents/add' => ['AbsenceController', 'markAbsent'],
        '/api/absents/add-justified' => ['AbsenceController', 'markJustifiedAbsent'],
        '/api/schedules/creneaux' => ['SchedulesController', 'getCreneaux'],
        '/api/schedules/{classe}' => ['SchedulesController', 'getByClass'],
        '/api/schedules' => ['SchedulesController', 'getAll'],
        '/api/classes' => ['ClassesController', 'getAll'],
        '/api/matieres' => ['CourseController', 'getAll'],
        '/api/matieres/{id}' => ['CourseController', 'getById'],
        '/api/export/csv' => ['HistoricalController', 'exportCSV'],
    ],
    'POST' => [
        '/login' => ['AuthController', 'verify'],
        '/scan/ajouter' => ['ScanController', 'ajouter'],
        '/search' => ['SearchController', 'search'],
        '/management/ajouter' => ['ManagementController', 'addStudent'],
        '/management/supprimer' => ['ManagementController', 'deleteStudent'],
        '/gestion/ajouter' => ['ManagementController', 'addStudent'],
        '/gestion/supprimer' => ['ManagementController', 'deleteStudent'],
        '/absent/ajouter' => ['AbsenceController', 'markAbsent'],

        // API Routes
            '/api/login' => ['AuthController', 'verify'],
            '/api/logout' => ['AuthController', 'logout'],
            '/api/absents/add' => ['AbsenceController', 'markAbsent'],
        '/api/scan' => ['ScanController', 'ajouter'],
        '/api/students/search' => ['StudentsController', 'search'],
        '/api/students/update' => ['StudentsController', 'update'],
        '/api/students/add' => ['StudentsController', 'add'],
        '/api/students/delete' => ['StudentsController', 'delete'],
        '/api/movements/delete' => ['MovementsController', 'delete'],
        '/api/movements/add' => ['MovementsController', 'add'],
        '/api/movements/search' => ['MovementsController', 'search'],
        '/api/movements/update' => ['MovementsController', 'update'],
        '/api/users/add' => ['UsersController', 'add'],
        '/api/users/delete' => ['UsersController', 'delete'],
        '/api/users/update' => ['UsersController', 'update'],
        '/api/schedules/add' => ['SchedulesController', 'add'],
        '/api/schedules/update' => ['SchedulesController', 'update'],
        '/api/schedules/delete' => ['SchedulesController', 'delete'],
        '/api/classes/add' => ['ClassesController', 'add'],
        '/api/classes/update' => ['ClassesController', 'update'],
        '/api/classes/delete' => ['ClassesController', 'delete'],
        '/api/matieres/search' => ['CourseController', 'search'],
        '/api/matieres/add' => ['CourseController', 'add'],
        '/api/matieres/update' => ['CourseController', 'update'],
        '/api/matieres/delete' => ['CourseController', 'delete'],
        '/api/absents/today' => ['AbsenceController', 'getTodayAbsents'],
        '/api/export/csv' => ['HistoricalController', 'exportCSV'],
    ]
];
